language: php
php:
  - 5.5
before_script:
  - composer install

script: 
  - php vendor/bin/phpunit --bootstrap test/bootstrap.php --coverage-clover build/logs/clover.xml test && php vendor/bin/coveralls -v

